services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DB}, ${TEST_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  docker-nest-postgres:
